package com.gitforge.backend.infrastructure;

import com.gitforge.backend.application.port.RepositoryGenerationPort;
import com.gitforge.backend.domain.model.RepositoryPreview;
import org.springframework.stereotype.Component;

@Component
public class FakeRepositoryGenerationAdapter implements RepositoryGenerationPort {

    @Override
    public RepositoryPreview generateRepositoryPreview(String prompt) {
        return new RepositoryPreview(
                "ecommerce-platform",
                "AI-generated ecommerce platform",
                "# Ecommerce Platform\n\nGenerated by GitForge AI."
        );
    }
}