package com.gitforge.backend.application;

import com.gitforge.backend.web.dto.GenerateRepositoryRequest;
import com.gitforge.backend.web.dto.RepositoryPreviewResponse;
import org.springframework.stereotype.Service;

@Service
public class GenerateRepositoryPreviewUseCase {

    public RepositoryPreviewResponse execute(GenerateRepositoryRequest request) {
        return new RepositoryPreviewResponse(
                "ecommerce-platform",
                "AI-generated ecommerce platform",
                "# Ecommerce Platform\n\nGenerated by GitForge AI."
        );
    }
}